- name: variables to print
  hosts: web
  vars:
    word: "I am learning"
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy M"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, {{word}}, {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"